# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Fotbal::Lite"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
session: Cookie
engines:
  session:
    Cookie:
      secret_key: your secret key
      default_duration: 600
    Simple:
      cookie_name: testapp.session
  template:
    template_toolkit:
      encoding: 'utf-8'
      INCLUDE_PATH: 'views'
      start_tag: '<%'
      end_tag: '%>' 
plugins:
    Database:
      driver: 'mysql'
      database: 'fotbal'
      host: 'localhost'
      port: 3306
      username: root
      password: 1

        # schema_class: Fotbal::My::Schema
        # dsn: DBI:mysql:dbname=fotbal
        # user: root
        # password: 1
        # options:
        #   PrintError: 1
        #   RaiseError: 1

# engines:
#   template:
#     template_toolkit:
#       start_tag: '<%'
#       end_tag:   '%>'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1
